src/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from .api import router as api_router
from .views import cached_javascript_catalog


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', cached_javascript_catalog, dict(packages=('project',))),

    url(r'^accounts/', include('accounts.urls')),

    url(r'^$', TemplateView.as_view(template_name='base.html'), name='home')
)

# api
urlpatterns += patterns(
    '',
    url(r'^api/auth/',
        include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(api_router.urls))
)

src/matchplan/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from model_utils import Choices, FieldTracker
from model_utils.models import (
    TimeStampedModel,
    StatusModel as UtilsStatusModel
)

from .mixins import StatsModelMixin


PRECISION = getattr(settings, 'POINTS_PRECISION', 2)

DEFAULT_GAME_DATABASE_CHOICES = (
    ('pes', _('PES')),
    ('fifa', _('FIFA'))
)

GAME_DATABASE_CHOICES = getattr(settings, 'GAME_DATABASE_CHOICES',
                                DEFAULT_GAME_DATABASE_CHOICES)


class StatusModel(UtilsStatusModel):

    def get_translated_status(self):
        return _(self.status)
    i18n_status = property(get_translated_status)

    class Meta:
        abstract = True


class Event(TimeStampedModel, StatusModel):
    """
    an event, duh!
    """

    STATUS = Choices('draft', 'running', 'finished')

    title = models.CharField(_('title'), max_length=100)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              verbose_name=_('owner'))

    power_factor_enabled = models.BooleanField(
        _('power factor?'),
        default=True,
        help_text=_('$$_power_factor_help_text_$$')
    )
    score_factor_enabled = models.BooleanField(
        _('score/goal factor?'),
        default=True,
        help_text=_('$$_score_factor_help_text_')
    )

    points_win = models.PositiveSmallIntegerField(
        _('points for win'), default=3, validators=[MinValueValidator(1)])
    points_draw = models.PositiveSmallIntegerField(
        _('points for draw/remis'), default=1,
        validators=[MinValueValidator(0)])
    points_loss = models.PositiveSmallIntegerField(
        _('points for loss'), default=0, validators=[MinValueValidator(0)])

    start = models.DateTimeField(_('start'), default=timezone.now)
    end = models.DateTimeField(_('end'), null=True, blank=True)

    game_database = models.CharField(
        _('game database'), max_length=10, choices=GAME_DATABASE_CHOICES,
        blank=True, default='', help_text=_('Used for auto-suggestions'))

    # tracker
    tracker = FieldTracker()

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        ordering = ('-start', '-created')

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        # from django.core.urlresolvers import reverse
        # return reverse('event_detail', args=[self.pk])
        return '/#/events/{0}'.format(self.pk)

    def get_status(self):
        # event status
        event_games = self.games.all()
        status = self.status

        if (event_games.filter(status=Game.STATUS.finished).count() ==
                event_games.count() and
                not status == self.STATUS.finished):
            # all matches are finished
            status = self.STATUS.finished
        elif (event_games.filter(status=Game.STATUS.finished).exists() and
                not status == self.STATUS.running):
            status = self.STATUS.running
        elif not status == self.STATUS.draft:
            status = self.STATUS.draft

        return status

    def get_users(self, as_id_list=False):
        """
        get all users for event (owner + players)
        set 'as_objects' to recieve id/pk list instead of queryset
        """
        user_pks = [self.owner_id]
        players = self.players.filter(status=Player.STATUS.active)
        user_pks += players.values_list('user_id', flat=True)
        user_pks = set(user_pks)
        if as_id_list:
            return user_pks
        return get_user_model().objects.filter(pk__in=user_pks)

    users = property(get_users)


class Player(StatsModelMixin, TimeStampedModel, StatusModel):
    """
    player(s) for an event
    """

    STATUS = Choices('active', 'inactive')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='players',
                             verbose_name=_('user'))
    event = models.ForeignKey(Event, related_name='players',
                              verbose_name=_('event'))
    number = models.PositiveSmallIntegerField(_('player number'), default=1)

    # tracker
    tracker = FieldTracker()

    # stats
    points = models.FloatField(
        _('points'),
        editable=False,
        null=True
    )
    points_per_game = models.FloatField(
        _('points per game'),
        editable=False,
        null=True
    )
    scores_for = models.PositiveSmallIntegerField(
        _('scores for'),
        editable=False,
        null=True
    )
    scores_against = models.PositiveSmallIntegerField(
        _('scores against'),
        editable=False,
        null=True
    )
    scores_for_per_game = models.FloatField(
        _('scores for per game'),
        editable=False,
        null=True
    )
    scores_against_per_game = models.FloatField(
        _('scores for per game'),
        editable=False,
        null=True
    )
    wins = models.PositiveSmallIntegerField(
        _('wins'),
        editable=False,
        null=True
    )
    draws = models.PositiveSmallIntegerField(
        _('draws'),
        editable=False,
        null=True
    )
    losses = models.PositiveSmallIntegerField(
        _('losses'),
        editable=False,
        null=True
    )

    stat_fields = ('points', 'points_per_game', 'scores_for',
                   'scores_for_per_game', 'scores_against',
                   'scores_against_per_game', 'wins', 'draws', 'losses')

    class Meta:
        verbose_name = _('player')
        verbose_name_plural = _('players')
        ordering = ('number',)
        unique_together = (('user', 'event'), ('event', 'number'))

    def __unicode__(self):
        return u"{} - #{} - {}".format(self.user, self.number, self.event)

    def get_initials(self):
        """
        get initials or first two chars of username
        """
        if self.user.first_name and self.user.last_name:
            return u'{}{}'.format(self.user.first_name[0],
                                  self.user.last_name[0])
        return self.user.username[:2]

    initials = property(get_initials)

    def get_games(self):
        """
        get all games for this player
        """

        if not self.pk:
            return Game.objects.none()

        home_games = list(self.games_home.values_list('pk', flat=True))
        away_games = list(self.games_away.values_list('pk', flat=True))
        return Game.objects.filter(pk__in=home_games + away_games)

    games = property(get_games)

    def get_scores_for(self):
        """
        get all scores/goals for player
        """

        if not self.pk:
            return 0

        qs_home = self.games_home.filter(status=Game.STATUS.finished)
        qs_away = self.games_away.filter(status=Game.STATUS.finished)
        scores_home = qs_home.values_list('score_home', flat=True)
        scores_away = qs_away.values_list('score_away', flat=True)
        return sum(scores_home) + sum(scores_away)

    def get_scores_for_per_game(self):
        games = self.games.filter(status=Game.STATUS.finished).count()
        if games:
            scores_per_game = float(self.scores_for) / float(games)
        else:
            scores_per_game = 0
        return float(format(scores_per_game, '.{0}f'.format(PRECISION)))

    def get_scores_against(self):
        """
        get all scores/goals against player
        """

        if not self.pk:
            return 0

        qs_home = self.games_home.filter(status=Game.STATUS.finished)
        qs_away = self.games_away.filter(status=Game.STATUS.finished)
        against_home = qs_home.values_list('score_away', flat=True)
        against_away = qs_away.values_list('score_home', flat=True)
        return sum(against_home) + sum(against_away)

    def get_scores_against_per_game(self):
        games = self.games.filter(status=Game.STATUS.finished).count()
        if games:
            scores_per_game = float(self.scores_against) / float(games)
        else:
            scores_per_game = 0
        return float(format(scores_per_game, '.{0}f'.format(PRECISION)))

    def get_points(self, formatted=True):
        """
        get all points for player (for finised games)
        """
        points = 0
        for game in self.games.filter(status=Game.STATUS.finished):
            if self in game.players_home.all():
                points += game.points_home
            elif self in game.players_away.all():
                points += game.points_away

        if formatted:
            points = float(format(points, '.{0}f'.format(PRECISION)))

        return points

    def get_points_per_game(self):
        games = self.games.filter(status=Game.STATUS.finished).count()
        if games:
            points_per_game = self.get_points(formatted=False) / games
        else:
            points_per_game = 0
        return float(format(points_per_game, '.{0}f'.format(PRECISION)))

    def get_user_initials(self):
        if not self.user.first_name or not self.user.last_name:
            return u"P{0}".format(self.pk)
        # TODO: check for duplicates!
        return u"{0}{1}".format(
            self.user.first_name[0],
            self.user.last_name[0]
        ).upper()

    user_initials = property(get_user_initials)

    def get_wins(self):
        wins = 0
        for game in self.games.filter(status=Game.STATUS.finished):
            if (self in game.players_home.all() and
                    game.score_home > game.score_away):
                wins += 1
            elif (self in game.players_away.all() and
                    game.score_away > game.score_home):
                wins += 1
        return wins

    def get_draws(self):
        draws = 0
        for game in self.games.filter(status=Game.STATUS.finished):

src/project/views.py
from django.utils import timezone
from django.views.decorators.http import last_modified
from django.views.i18n import javascript_catalog


@last_modified(lambda req, **kw: timezone.now())
def cached_javascript_catalog(request, domain='djangojs', packages=None):
    return javascript_catalog(request, domain, packages)

src/project/templates/angular/_dashboard.html
{% load trans from i18n %}

<script type="text/ng-template" id="dashboard.html">
  <div class="dashboard">
    <h4>{% trans "Dashboard" %}</h4>

    <section class="dshbrd-events">

      <a href="/#/events">
        <h5 class="headline z-depth-1">
          <i class="mdi-navigation-arrow-forward left"></i>
          {% trans "events" %}
        </h5>
      </a>

      <div ng-class="{card: true, animated: event.entrance, flash: event.entrance}"
           ng-repeat="event in events | orderBy: '-start'">
        <div class="card-content">
          {% verbatim %}
          <h5>{{ event.title }}</h5>
          <p class="secondary">
            {{ event.start|moment:'LLL' }} ·
            {{ event.i18n_status }} ·
            {{ event.players.length }} {% endverbatim %}{% trans "players" %}{% verbatim %} ·
            {{ event.event_games.length }} {% endverbatim %}{% trans "games" %}{% verbatim %}
          </p>
        </div>
        <div class="card-action">
          <a href="/#/events/{{ event.id }}/" class="more">
            <i class="mdi-navigation-arrow-forward left"></i>
            {% endverbatim %}{% trans "detail" %}
          </a>
        </div>
      </div>

      <div ng-hide="events_loaded">
        {% include "_loader.html" %}
      </div>

      <div ng-show="events_loaded && !events.length" class="col s12 empty center-align">
        <i class="secondary">{% trans "No events" %}</i>
      </div>

    </section>

    <section class="dshbrd-games">

      {% comment %}
      <a href="/#/games/">
        <h5 class="headline">
          <i class="mdi-navigation-arrow-forward left"></i>
          {% trans "games" %}
        </h5>
      </a>
      {% endcomment %}
      <h5 class="headline z-depth-1">{% trans "latest games" %}</h5>

      <div class="row">
        <div class="col s12 game" ng-repeat="game in games | orderBy: '-id'">
          {% verbatim %}
            <div ng-class="{card: true, animated: game.entrance, flash: game.entrance}">
              <div class="card-content">
                <i class="mdi-navigation-more-vert right activator secondary"></i></span>
                <span class="secondary title">
                  {{ game.event.title }} #{{ game.number }}
                </span>

                <div class="row home">
                  <div class="col s12">
                    <div ng-show="game.players_home.length">
                      <span class="player" ng-repeat="player in game.players_home">
                        <span class="number">#{{ player.number }}</span>
                        <span class="user-badge" title="{{ player.user.user_name }}">
                          {{ player.user.initials }}
                        </span>
                      </span>
                    </div>
                    <h5>
                      <span ng-show="game.team_home">{{ game.team_home }}</span>
                      <span ng-hide="game.team_home" class="secondary">
                        {% endverbatim %}{% trans "Team Home" %}{% verbatim %}
                      </span>
                      <span class="secondary power" ng-show="game.power_home">({{ game.power_home }})</span>
                      <span class="right-align right score">{{ game.score_home }}</span>
                    </h5>
                  </div>
                </div>

                <div class="row away">
                  <div class="col s12">
                    <h5>
                      <span ng-show="game.team_away">{{ game.team_away }}</span>
                      <span ng-hide="game.team_away" class="secondary">
                        {% endverbatim %}{% trans "Team Away" %}{% verbatim %}
                      </span>
                      <span class="secondary power" ng-show="game.power_away">({{ game.power_away }})</span>
                      <span class="right-align right score">{{ game.score_away }}</span>
                    </h5>
                    <div ng-show="game.players_away.length">
                      <span class="player" ng-repeat="player in game.players_away">
                        <span class="number">#{{ player.number }}</span>
                        <span class="user-badge" title="{{ player.user.user_name }}">
                          {{ player.user.initials }}
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              <div class="card-action">
                <a href="/#/events/{{ game.event.id }}/" class="more">
                  <i class="mdi-navigation-arrow-forward left"></i>
                  {% endverbatim %}{% trans "event" %}{% verbatim %}
                </a>
              </div>

              <div class="card-reveal">
                <h5 class="card-title">
                  {% endverbatim %}{% trans "game details" %}{% verbatim %}
                  <i class="mdi-navigation-close right"></i>
                </h5>
                <ul class="collection">
                  <li class="collection-item">
                    <div>
                      {% endverbatim %}{% trans "power factor" %}{% verbatim %}
                      <span class="secondary-content">{{ game.power_factor | to_fixed: 2 }}</span>
                    </div>
                  </li>
                  <li class="collection-item">
                    <div>
                      {% endverbatim %}{% trans "score factor" %}{% verbatim %}
                      <span class="secondary-content">{{ game.score_factor | to_fixed: 2 }}</span>
                    </div>
                  </li>
                  <li class="collection-item">
                    <div>
                      {% endverbatim %}{% trans "points" %}{% verbatim %} {{ game.team_home }}
                      <span class="secondary-content">{{ game.points_home | to_fixed: 2 }}</span>
                    </div>
                  </li>
                  <li class="collection-item" ng-show="game.event.score_factor_enabled">
                    <div>
                      {% endverbatim %}{% trans "points" %}{% verbatim %} {{ game.team_away }}
                      <span class="secondary-content">{{ game.points_away | to_fixed: 2 }}</span>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          {% endverbatim %}
        </div>

        <div ng-hide="games_loaded">
          {% include "_loader.html" %}
        </div>

        <div ng-show="games_loaded && !games.length" class="col s12 game empty center-align">
          <i class="secondary">{% trans "No games" %}</i>
        </div>
      </div>

    <section>

  </div>

</script>

src/project/templates/angular/_event_form.html
{% load trans from i18n %}

<form accept-charset="utf-8" ng-submit="save()" class="row form" name="event-form">

  <div class="col s12">
    <div class="col s12">
      <p>
        <label for="id_title">{% trans "title" %}</label>
        <input id="id_title" type="text" ng-model="event.title" required
               ng-disabled="event.id && event.owner !== user_id" />
      </p>
    </div>
  </div>

  <div class="col s12 m6">

    <div class="col s6 m12 l6">
      <div class="switch">
        <p class="center-align">
          <label>
            <input type="checkbox" ng-model="event.power_factor_enabled"
                   ng-disabled="event.id && event.owner !== user_id">
            <span class="lever"></span>
            {% trans "power factor?" %}
          </label>
        </p>
      </div>
    </div>

    <div class="col s6 m12 l6">
      <div class="switch">
        <p class="center-align">
          <label>
            <input type="checkbox" ng-model="event.score_factor_enabled"
                   ng-disabled="event.id && event.owner !== user_id">
            <span class="lever"></span>
            {% trans "score factor?" %}
          </label>
        </p>
      </div>
    </div>
  </div>

  <div class="col s12 m6">

    <div class="col s4 center">
      <p>
        <label for="id_points_win">{% trans "points for win" %}</label>
        <input type="number" min="1" ng-model="event.points_win" required
               ng-disabled="event.id && event.owner !== user_id" />
      </p>
    </div>

    <div class="col s4 center">
      <p>
        <label for="id_points_draw">{% trans "points for draw" %}</label>
        <input type="number" min="0" ng-model="event.points_draw" required
               ng-disabled="event.id && event.owner !== user_id"/>
      </p>
    </div>

    <div class="col s4 center">
      <p>
        <label for="id_points_loss">{% trans "points for loss" %}</label>
        <input type="number" min="0" ng-model="event.points_loss" required
               ng-disabled="event.id && event.owner !== user_id" />
      </p>
    </div>

  </div>

  <div class="col s12">
    <div class="col s12 m6 center">
      <p>
        <label for="id_start">{% trans "start" %}</label>
        <input type="datetime-local" ng-model="event.start" required
               id="id_start" ng-disabled="event.id && event.owner !== user_id" />
      </p>
    </div>
    <div class="col s12 m6 center">
      <p>
        <label>{% trans "Game database" %}</label>
        <select ng-model="event.game_database"
                ng-disabled="event.id && event.owner !== user_id">
          <option value=""></option>
          {% for key, name in GAME_DATABASES %}
            <option value="{{ key }}">{{ name }}</option>
          {% endfor %}
        </select>
      </p>
    </div>
  </div>

  <div class="col s12">
    <div class="col s12">
      {% trans "Players" %}
      <ul class="collection sortable" ng-show="event.players.length">
        {% verbatim %}
        <li class="player collection-item" ng-repeat="player in event.players | orderBy: 'number'" data-id="{{ player.user.id }}">
          <span class="number secondary">#{{ player.number }}</span>
          <span>{{ player.user.user_name }}</span>
          <a class="secondary-content" ng-hide="event.id && event.owner !== user_id">
            <i class="mdi-content-remove-circle-outline" ng-click="removePlayer(player)"></i>
          </a>
        </li>
        {% endverbatim %}
      </ul>
      <p ng-hide="event.players.length">
        <i>{% trans "No players" %}</i>
      </p>
      <div ng-show="available_users.length && ((event.id && event.owner === user_id) || !event.id)">
        <label>{% trans "Add player" %}</label>
        <select ng-change="addPlayer()" ng-model="new_player">
          {% verbatim %}
            <option value="{{ user.id }}" ng-repeat="user in available_users | orderBy: 'user_name'">{{ user.user_name }}</option>
          {% endverbatim %}
        </select>
      </div>
    </div>
  </div>

  <div class="col s12" ng-hide="event.id && event.owner !== user_id">
    <p class="center-align">
      <button type="submit" class="btn">
        <i class="mdi-action-done left" ng-hide="syncing"></i>
        <i class="mdi-notification-sync left animated infinite flash" ng-show="syncing"></i>
        {% trans "save" %}
      </button>
    </p>
  </div>

</form>

src/project/templates/angular/_event_list.html
{% load trans from i18n %}

<script type="text/ng-template" id="event_list.html">

  <div class="events">

    <h5 class="headline z-depth-1">
      <a class="btn-floating waves-effect waves-light right modal-trigger"
         ng-click="openModal('#event-form')" title="{% trans "Add event" %}">
        <i class="mdi-content-add"></i>
      </a>
      {% trans "events" %}
    </h5>

    <div ng-class="{card: true, animated: event.entrance, flash: event.entrance}"
         ng-repeat="event in events | orderBy: '-start'">
      <div class="card-content">
        {% verbatim %}
        <h5>{{ event.title }}</h5>
        <p class="secondary">
          {{ event.start|moment:'LLL' }} ·
          {{ event.i18n_status }} ·
          {{ event.players.length }} {% endverbatim %}{% trans "players" %}{% verbatim %} ·
          {{ event.event_games.length }} {% endverbatim %}{% trans "games" %}{% verbatim %}
        </p>
      </div>
      <div class="card-action">
        <a href="/#/events/{{ event.id }}/" class="more">
          <i class="mdi-navigation-arrow-forward left"></i>
          {% endverbatim %}{% trans "detail" %}
        </a>
      </div>
    </div>

    <div ng-hide="events_loaded">
      {% include "_loader.html" %}
    </div>

    <div ng-show="events_loaded && !events.length" class="col s12 empty center-align">
      <i class="secondary">{% trans "No events" %}</i>
    </div>

    <div class="center-align" ng-show="next">
      <a href="{{ next }}" ng-click="loadEvents(next)">
        {% trans "more" %}<br />
        <i class="mdi-navigation-expand-more"></i>
      </a>
    </div>

  </div>

  <div id="event-form" class="modal">
    <div class="modal-content">
      <i class="mdi-navigation-close small right" title="{% trans "close" %}" ng-click="closeModal('#event-form');"></i>
      <h4>{% trans "Create event" %}</h4>
      {% include "angular/_event_form.html" %}
    </div>
  </div>
</script>

src/project/templates/angular/_game_form.html
{% load trans from i18n %}

<form accept-charset="utf-8" ng-submit="saveGame()" class="row form" name="game-form">

  <div class="col s12 m6">

    <h5>{% trans "Team Home" %}</h5>

    <div class="col s12">
      {% verbatim %}
      <ul class="collection" ng-show="game.players_home.length">
        <li class="collection-item" ng-repeat="player in game.players_home | get_player_objects:event.players | orderBy: 'number'">
          <span class="secondary">#{{ player.number }}</span>
          <span class="name">{{ player.user.user_name }}</span>
          <a class="secondary-content">
            <i class="mdi-content-remove-circle-outline" ng-click="removeGamePlayer(player)"></i>
          </a>
        </li>
      </ul>
      {% endverbatim %}

      <p ng-hide="game.players_home.length + game.players_away.length == event.players.length">
        <label>{% trans "Add player" %}</label>
        <select ng-change="addGamePlayer('home')" ng-model="new_home_player">
          {% verbatim %}
            <option value="{{ player.id }}" ng-repeat="player in event.players | get_unassigned_players:game | orderBy: 'user.user_name'">
              {{ player.user.user_name }}
            </option>
          {% endverbatim %}
        </select>
      </p>
    </div>

    <div class="col s12" ng-hide="event.power_factor_enabled">
      <label for="id_home_team">{% trans "team" %}</label>
      <input type="text" ng-model="game.team_home" required id="id_home_team" list='teams'
        ng-keyup="searchTeam('team_home')" ng-change="applyTeam('home')"
        ng-blur="teams = []; last_search = '';" />
    </div>

    <div class="col s8" ng-show="event.power_factor_enabled">
      <label for="id_home_team">{% trans "team" %}</label>
      <input type="text" ng-model="game.team_home" required id="id_home_team" list='teams'
        ng-keyup="searchTeam('team_home')" ng-change="applyTeam('home')"
        ng-blur="teams = []; last_search = '';" />
    </div>

    <div class="col s4" ng-show="event.power_factor_enabled">
      <label for="id_home_team_power">{% trans "power" %}</label>
      <input type="number" ng-model="game.power_home" id="id_home_team_power" min="0" max="100" />
    </div>

  </div>


  <div class="col s12 m6">

    <h5>{% trans "Team Away" %}</h5>

    <div class="col s12">

      {% verbatim %}
      <ul class="collection" ng-show="game.players_away.length">
        <li class="collection-item" ng-repeat="player in game.players_away | get_player_objects:event.players | orderBy: 'number'">
          <span class="secondary">#{{ player.number }}</span>
          <span class="name">{{ player.user.user_name }}</span>
          <a class="secondary-content">
            <i class="mdi-content-remove-circle-outline" ng-click="removeGamePlayer(player)"></i>
          </a>
        </li>
      </ul>
      {% endverbatim %}

      <p ng-hide="game.players_home.length + game.players_away.length == event.players.length">
        <label>{% trans "Add player" %}</label>
        <select ng-change="addGamePlayer('away')" ng-model="new_away_player">
          {% verbatim %}
            <option value="{{ player.id }}" ng-repeat="player in event.players | get_unassigned_players:game | orderBy: 'user.user_name'">
              {{ player.user.user_name }}
            </option>
          {% endverbatim %}
        </select>
      </p>

    </div>

    <div class="col s12" ng-hide="event.power_factor_enabled">
      <label for="id_away_team">{% trans "team" %}</label>
      <input type="text" ng-model="game.team_away" required id="id_away_team" list='teams'
        ng-keyup="searchTeam('team_away')" ng-change="applyTeam('away')"
        ng-blur="teams = []; last_search = '';" />
    </div>

    <div class="col s8" ng-show="event.power_factor_enabled">
      <label for="id_away_team">{% trans "team" %}</label>
      <input type="text" ng-model="game.team_away" required id="id_away_team" list='teams'
        ng-keyup="searchTeam('team_away')" ng-change="applyTeam('away')"
        ng-blur="teams = []; last_search = '';" />
    </div>

    <div class="col s4" ng-show="event.power_factor_enabled">
      <label for="id_away_team_power">{% trans "power" %}</label>
      <input type="number" ng-model="game.power_away" id="id_away_team_power" min="0" max="100" />
    </div>

  </div>

  <div class="col s12">
    <div class="col s6 m4 l3">
      <label for="id_game_number">{% trans "Number" %}</label>
      <input type="number" min="1" ng-model="game.number" id="id_game_number" />
    </div>
  </div>


  <div class="col s12">

    <p class="center-align">
      <button type="submit" class="btn">
        <i class="mdi-action-done left" ng-hide="syncing"></i>
        <i class="mdi-notification-sync left animated infinite flash" ng-show="syncing"></i>
        {% trans "save" %}
      </button>
    </p>
  </div>

  <datalist id="teams">
    {% verbatim %}
      <option value="{{ team.name }}" ng-repeat="team in teams | orderBy: 'name'"
       label="{{ team | get_datalist_value: event.power_factor_enabled }}">
       {{ team | get_datalist_value: event.power_factor_enabled }}
     </option>
    {% endverbatim %}
  </datalist>

</form>

src/project/templates/angular/_score_form.html
{% load trans from i18n %}

<form method="post" accept-charset="utf-8" ng-submit="saveScore()" class="row form" name="score-form">

    <div class="col s12 m6">
      <h6 class="center secondary">{% trans "Team Home" %}</h5>
      {% verbatim %}
      <h5 ng-show="game.team_home" class="center-align">
        {{ game.team_home }}
      </h5>
      <h6 ng-repeat="player in game.players_home | get_player_objects: event.players" class="center-align">
        #{{ player.number }} {{ player.user.user_name }}
      </h6>
      {% endverbatim %}
      <div class="col s6 offset-s3">
        <input type="number" min="0" ng-model="game.score_home">
      </div>
    </div>

    <div class="col s12 m6">
      <h6 class="center secondary">{% trans "Team Away" %}</h6>
      {% verbatim %}
      <h5 ng-show="game.team_away" class="center-align">
        {{ game.team_away }}
      </h5>
      <h6 ng-repeat="player in game.players_away | get_player_objects: event.players" class="center-align">
        #{{ player.number }} {{ player.user.user_name }}
      </h6>
      {% endverbatim %}
      <div class="col s6 offset-s3">
        <input type="number" min="0" ng-model="game.score_away">
      </div>
    </div>

    <div class="col s12 m4 center-align">
      <input type="radio" name="status" ng-model="game.status" value="scheduled" id="status-scheduled" />
      <label for="status-scheduled">{% trans "scheduled" %}</label>
    </div>
    <div class="col s12 m4 center-align">
      <input type="radio" name="status" ng-model="game.status" value="running" id="status-running" />
      <label for="status-running">{% trans "running" %}</label>
    </div>
    <div class="col s12 m4 center-align">
      <input type="radio" name="status" ng-model="game.status" value="finished" id="status-finished" />
      <label for="status-finished">{% trans "finished" %}</label>
    </div>

    <div class="col s10 offset-s1">

    <p class="center-align">
      <button type="submit" class="btn">
        <i class="mdi-action-done left" ng-hide="syncing"></i>
        <i class="mdi-notification-sync left animated infinite flash" ng-show="syncing"></i>
        {% trans "save" %}
      </button>
    </p>
  </div>

</form>